# Generated by Django 4.2.6 on 2023-11-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=100)),
                ('numberOfReviews', models.IntegerField()),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('weight', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
